version: "3"

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - app-network

  redis-commander:
    depends_on:
      - redis
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
    ports:
      - 8081:8081
    networks:
      - app-network

  express-ioredis:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: developer.dockerfile
    image: express-ioredis
    container_name: express-ioredis
    ports:
      - "5000:5000"
    environment:
      APP_PORT: 5000
      REDIS_PORT: 6379
      REDIS_HOST: redis
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    command: >
      bash -c "
        npm run app:typecheck
        npm run app:lint
        npm run app:build
        npm run app:start:dev
      "
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis:
  redis-config:
  node_modules:
